### PR TITLE
include fsharp project files when adding a package

### PR DESCRIPTION
**Pull request by WillEhrendreich**
adds fsharp project files in. Hope you try fsharp out! You would love it, I know I do.

### CODE REVIEW

**Comment by MoaidHathot** [comment]
Hi, I will review it soon, thanks for the contribution!

**Comment by MoaidHathot** [comment]
@WillEhrendreich, this PR contain a lot of formatting changes that makes it very hard to review. Could you please revert the formatting changes and keep only the functional changes so that it is easy to review?
If you think the formatting changes are important, please open a new PR/Issue about it.

**Comment by WillEhrendreich** [comment]
Oh man, I honestly didn't realize that, it was done by lazyvim's auto format on save. I'll try to clean that up.

**Comment by WillEhrendreich** [comment]
@MoaidHathot I've cleaned it up, let me know what you think :)

**Review by MoaidHathot — APPROVED** [review]
I modified the files a bit but good job and thank you for the contribution :)

**Pull request merged**
